In [5]:
import pandas as pd
df = pd.read_csv(r'D:\task_folder\sources\IND_prep\data\loans\loans.csv')

In [6]:
df.head()

,total_credit_utilized,installment,grade,state,issue_date,application_time,accounts,y,vector_feature,non_decimal_feature,sentence_feature
0,38767,652.53,C,NJ,16-Apr-18,28:43.3,"{""current_delinq"":0,""current_installment"":2,""o...",0,"[3.03, 5.92, 0.95, 7.29, 3.68]",0b11011001,배터리 잔량 부족
1,4321,167.54,C,HI,13-Feb-18,43:08.5,"{""current_delinq"":0,""current_installment"":0,""o...",0,"[4.1, 1.11, 4.34, 3.13, 6.4]",0b1000110001,센서 값 정상 범위
2,16000,71.40,D,WI,23-Mar-18,44:08.2,"{""current_delinq"":0,""current_installment"":1,""o...",0,"[8.17, 4.8, 4.53, 9.54, 6.86]",0x2f,정기 점검 완료
3,4997,664.19,A,PA,09-Jan-18,32:42.6,"{""current_delinq"":0,""current_installment"":1,""o...",0,"[1.83, 4.44, 5.1, 7.02, 6.71]",0x124,모터 온도 상승 경고
4,52722,786.87,C,CA,08-Apr-18,33:13.3,"{""current_delinq"":0,""current_installment"":1,""o...",0,"[2.54, 6.9, 5.92, 1.53, 7.17]",0xe0,정기 점검 완료

In [7]:
df['sentence_feature']

0         배터리 잔량 부족
1        센서 값 정상 범위
2          정기 점검 완료
3       모터 온도 상승 경고
4          정기 점검 완료
           ...
9995    시스템 업데이트 필요
9996    초기화 작업 진행 중
9997      데이터 처리 성공
9998       정기 점검 완료
9999     분석 보고서 생성됨
Name: sentence_feature, Length: 10000, dtype: object

In [ ]:
# import pandas as pd
# df_ori = pd.read_csv(r'D:\task_folder\sources\IND_prep\data\loans\loans_2024.csv',encoding='utf-8')
# df = pd.read_csv(r'D:\task_folder\sources\IND_prep\data\loans\loans.csv',encoding='cp949')
# df['application_time']=df_ori['application_time']
# df.to_csv(r'D:\task_folder\sources\IND_prep\data\loans\loans.csv',index=False)

In [7]:
df_ori.head()

,total_credit_utilized,installment,grade,state,issue_date,application_time,accounts,y
0,38767,652.53,C,NJ,16-Apr-18,13:28:43.3,"{""current_delinq"":0,""current_installment"":2,""o...",0
1,4321,167.54,C,HI,13-Feb-18,10:43:08.5,"{""current_delinq"":0,""current_installment"":0,""o...",0
2,16000,71.40,D,WI,23-Mar-18,15:44:08.2,"{""current_delinq"":0,""current_installment"":1,""o...",0
3,4997,664.19,A,PA,09-Jan-18,11:32:42.6,"{""current_delinq"":0,""current_installment"":1,""o...",0
4,52722,786.87,C,CA,08-Apr-18,10:33:13.3,"{""current_delinq"":0,""current_installment"":1,""o...",0

In [10]:
import pandas as pd
df = pd.read_csv(r'D:\task_folder\sources\IND_prep\data\loans\loans.csv',encoding='utf-8')

In [14]:
df['non_decimal_feature']

0         0b11011001
1       0b1000110001
2               0x2f
3              0x124
4               0xe0
            ...
9995    0b1111100100
9996     0b111100101
9997           0x156
9998           0x1b1
9999           0x244
Name: non_decimal_feature, Length: 10000, dtype: object

In [18]:
cols = 'non_decimal_feature'

In [19]:
import numpy as np

def parse_non_decimal(val):
    try:
        if isinstance(val, str):
            val = val.lower().strip()
            if val.startswith('0b'):
                return int(val, 2)  # 2진수
            elif val.startswith('0x'):
                return int(val, 16)  # 16진수
            else:
                return int(val)  # 10진수 가정
        return val
    except (ValueError, TypeError):
        return np.nan
df[cols].apply(parse_non_decimal)

0       217
1       561
2        47
3       292
4       224
       ...
9995    996
9996    485
9997    342
9998    433
9999    580
Name: non_decimal_feature, Length: 10000, dtype: int64